import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Adding extra books...');

  // 추가 책 데이터 - 다양한 언어의 표지가 있는 책들
  const extraBooks = [
    // 영어 추가 책들
    {
      title: 'The Iliad',
      author: 'Homer',
      description: 'The ancient Greek epic poem about the Trojan War.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'HARD' as const,
      publishedYear: -750,
      gutenbergId: '6130',
      epubUrl: 'https://www.gutenberg.org/ebooks/6130.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/6130/pg6130.cover.medium.jpg',
    },
    {
      title: 'Emma',
      author: 'Jane Austen',
      description: 'A comedy of manners about a young woman who fancies herself a matchmaker.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1815,
      gutenbergId: '158',
      epubUrl: 'https://www.gutenberg.org/ebooks/158.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/158/pg158.cover.medium.jpg',
    },
    {
      title: 'Sense and Sensibility',
      author: 'Jane Austen',
      description: 'The story of the Dashwood sisters and their pursuit of happiness.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1811,
      gutenbergId: '161',
      epubUrl: 'https://www.gutenberg.org/ebooks/161.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/161/pg161.cover.medium.jpg',
    },
    {
      title: 'Persuasion',
      author: 'Jane Austen',
      description: 'The story of Anne Elliot who is persuaded to break off her engagement.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1817,
      gutenbergId: '105',
      epubUrl: 'https://www.gutenberg.org/ebooks/105.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/105/pg105.cover.medium.jpg',
    },
    {
      title: 'Northanger Abbey',
      author: 'Jane Austen',
      description: 'A satire of Gothic novels following a young woman invited to stay at an abbey.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1817,
      gutenbergId: '121',
      epubUrl: 'https://www.gutenberg.org/ebooks/121.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/121/pg121.cover.medium.jpg',
    },
    {
      title: 'David Copperfield',
      author: 'Charles Dickens',
      description: 'A semi-autobiographical novel chronicling the life of David Copperfield.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1850,
      gutenbergId: '766',
      epubUrl: 'https://www.gutenberg.org/ebooks/766.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/766/pg766.cover.medium.jpg',
    },
    {
      title: 'A Christmas Carol',
      author: 'Charles Dickens',
      description: 'The story of Ebenezer Scrooge and his transformation on Christmas Eve.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1843,
      gutenbergId: '46',
      epubUrl: 'https://www.gutenberg.org/ebooks/46.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/46/pg46.cover.medium.jpg',
    },
    {
      title: 'Bleak House',
      author: 'Charles Dickens',
      description: 'A novel that satirizes the British judiciary system.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1853,
      gutenbergId: '1023',
      epubUrl: 'https://www.gutenberg.org/ebooks/1023.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1023/pg1023.cover.medium.jpg',
    },
    {
      title: 'The Brothers Karamazov',
      author: 'Fyodor Dostoevsky',
      description: 'A philosophical novel that explores faith, doubt, and the nature of evil.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1880,
      gutenbergId: '28054',
      epubUrl: 'https://www.gutenberg.org/ebooks/28054.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/28054/pg28054.cover.medium.jpg',
    },
    {
      title: 'Anna Karenina',
      author: 'Leo Tolstoy',
      description: 'A tragic love story set against the backdrop of Russian high society.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1877,
      gutenbergId: '1399',
      epubUrl: 'https://www.gutenberg.org/ebooks/1399.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1399/pg1399.cover.medium.jpg',
    },
    {
      title: 'The Invisible Man',
      author: 'H.G. Wells',
      description: 'A scientist discovers how to make himself invisible but cannot reverse it.',
      language: 'EN' as const,
      genre: 'SCIENCE_FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1897,
      gutenbergId: '5230',
      epubUrl: 'https://www.gutenberg.org/ebooks/5230.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/5230/pg5230.cover.medium.jpg',
    },
    {
      title: 'The Island of Doctor Moreau',
      author: 'H.G. Wells',
      description: 'A shipwrecked man discovers an island inhabited by strange creatures.',
      language: 'EN' as const,
      genre: 'SCIENCE_FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1896,
      gutenbergId: '159',
      epubUrl: 'https://www.gutenberg.org/ebooks/159.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/159/pg159.cover.medium.jpg',
    },
    {
      title: 'The Call of the Wild',
      author: 'Jack London',
      description: 'A dog named Buck is stolen and sold into service as a sled dog in Alaska.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1903,
      gutenbergId: '215',
      epubUrl: 'https://www.gutenberg.org/ebooks/215.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/215/pg215.cover.medium.jpg',
    },
    {
      title: 'White Fang',
      author: 'Jack London',
      description: 'The story of a wild wolf-dog hybrid and his journey to domestication.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1906,
      gutenbergId: '910',
      epubUrl: 'https://www.gutenberg.org/ebooks/910.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/910/pg910.cover.medium.jpg',
    },
    {
      title: 'The Adventures of Tom Sawyer',
      author: 'Mark Twain',
      description: 'The mischievous adventures of a young boy growing up along the Mississippi River.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1876,
      gutenbergId: '74',
      epubUrl: 'https://www.gutenberg.org/ebooks/74.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/74/pg74.cover.medium.jpg',
    },
    {
      title: 'Adventures of Huckleberry Finn',
      author: 'Mark Twain',
      description: 'Huck Finn and Jim, a runaway slave, travel down the Mississippi River.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1884,
      gutenbergId: '76',
      epubUrl: 'https://www.gutenberg.org/ebooks/76.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/76/pg76.cover.medium.jpg',
    },
    {
      title: 'The Prince and the Pauper',
      author: 'Mark Twain',
      description: 'Two boys, one a prince and one a pauper, trade places.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1881,
      gutenbergId: '1837',
      epubUrl: 'https://www.gutenberg.org/ebooks/1837.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1837/pg1837.cover.medium.jpg',
    },
    {
      title: 'A Connecticut Yankee in King Arthurs Court',
      author: 'Mark Twain',
      description: 'A 19th-century American is transported back to medieval England.',
      language: 'EN' as const,
      genre: 'FANTASY' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1889,
      gutenbergId: '86',
      epubUrl: 'https://www.gutenberg.org/ebooks/86.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/86/pg86.cover.medium.jpg',
    },
    {
      title: 'The Importance of Being Earnest',
      author: 'Oscar Wilde',
      description: 'A comedic play about two men who both use the name Ernest to escape obligations.',
      language: 'EN' as const,
      genre: 'DRAMA' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1895,
      gutenbergId: '844',
      epubUrl: 'https://www.gutenberg.org/ebooks/844.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/844/pg844.cover.medium.jpg',
    },
    {
      title: 'The Wonderful Wizard of Oz',
      author: 'L. Frank Baum',
      description: 'Dorothy is swept away to a magical land and must find her way home.',
      language: 'EN' as const,
      genre: 'FANTASY' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1900,
      gutenbergId: '55',
      epubUrl: 'https://www.gutenberg.org/ebooks/55.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/55/pg55.cover.medium.jpg',
    },
    {
      title: 'Peter Pan',
      author: 'J.M. Barrie',
      description: 'The adventures of Peter Pan, a boy who never grows up.',
      language: 'EN' as const,
      genre: 'FANTASY' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1911,
      gutenbergId: '16',
      epubUrl: 'https://www.gutenberg.org/ebooks/16.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/16/pg16.cover.medium.jpg',
    },
    {
      title: 'The Secret Garden',
      author: 'Frances Hodgson Burnett',
      description: 'A spoiled young girl discovers a hidden garden and finds healing.',
      language: 'EN' as const,
      genre: 'CHILDREN' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1911,
      gutenbergId: '113',
      epubUrl: 'https://www.gutenberg.org/ebooks/113.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/113/pg113.cover.medium.jpg',
    },
    {
      title: 'A Little Princess',
      author: 'Frances Hodgson Burnett',
      description: 'A young girl at a boarding school faces poverty with grace and imagination.',
      language: 'EN' as const,
      genre: 'CHILDREN' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1905,
      gutenbergId: '146',
      epubUrl: 'https://www.gutenberg.org/ebooks/146.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/146/pg146.cover.medium.jpg',
    },
    {
      title: 'Through the Looking Glass',
      author: 'Lewis Carroll',
      description: 'Alice enters a fantastical world through a mirror.',
      language: 'EN' as const,
      genre: 'FANTASY' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1871,
      gutenbergId: '12',
      epubUrl: 'https://www.gutenberg.org/ebooks/12.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/12/pg12.cover.medium.jpg',
    },
    {
      title: 'The Metamorphosis',
      author: 'Franz Kafka',
      description: 'A man wakes up one morning to find himself transformed into a giant insect.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1915,
      gutenbergId: '5200',
      epubUrl: 'https://www.gutenberg.org/ebooks/5200.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/5200/pg5200.cover.medium.jpg',
    },
    {
      title: 'The Yellow Wallpaper',
      author: 'Charlotte Perkins Gilman',
      description: 'A woman descends into madness while confined to a room by her physician husband.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1892,
      gutenbergId: '1952',
      epubUrl: 'https://www.gutenberg.org/ebooks/1952.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1952/pg1952.cover.medium.jpg',
    },
    {
      title: 'Ethan Frome',
      author: 'Edith Wharton',
      description: 'A tragic tale of forbidden love in rural New England.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1911,
      gutenbergId: '4517',
      epubUrl: 'https://www.gutenberg.org/ebooks/4517.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/4517/pg4517.cover.medium.jpg',
    },
    {
      title: 'The Age of Innocence',
      author: 'Edith Wharton',
      description: 'A Pulitzer Prize-winning novel about New York society in the 1870s.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1920,
      gutenbergId: '541',
      epubUrl: 'https://www.gutenberg.org/ebooks/541.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/541/pg541.cover.medium.jpg',
    },
    {
      title: 'The House of Mirth',
      author: 'Edith Wharton',
      description: 'The story of Lily Bart and her struggle to find a place in New York society.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1905,
      gutenbergId: '284',
      epubUrl: 'https://www.gutenberg.org/ebooks/284.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/284/pg284.cover.medium.jpg',
    },
    {
      title: 'The Turn of the Screw',
      author: 'Henry James',
      description: 'A ghost story about a governess who believes her charges are being corrupted.',
      language: 'EN' as const,
      genre: 'HORROR' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1898,
      gutenbergId: '209',
      epubUrl: 'https://www.gutenberg.org/ebooks/209.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/209/pg209.cover.medium.jpg',
    },
    {
      title: 'Daisy Miller',
      author: 'Henry James',
      description: 'A novella about a young American woman in Europe.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1878,
      gutenbergId: '208',
      epubUrl: 'https://www.gutenberg.org/ebooks/208.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/208/pg208.cover.medium.jpg',
    },
    {
      title: 'The Portrait of a Lady',
      author: 'Henry James',
      description: 'The story of Isabel Archer, a young American woman who inherits a fortune.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1881,
      gutenbergId: '2833',
      epubUrl: 'https://www.gutenberg.org/ebooks/2833.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2833/pg2833.cover.medium.jpg',
    },
    {
      title: 'The Red Badge of Courage',
      author: 'Stephen Crane',
      description: 'A psychological portrait of fear and courage during the American Civil War.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1895,
      gutenbergId: '73',
      epubUrl: 'https://www.gutenberg.org/ebooks/73.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/73/pg73.cover.medium.jpg',
    },
    {
      title: 'The Awakening',
      author: 'Kate Chopin',
      description: 'A woman struggles with societal expectations in late 19th century Louisiana.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1899,
      gutenbergId: '160',
      epubUrl: 'https://www.gutenberg.org/ebooks/160.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/160/pg160.cover.medium.jpg',
    },
    {
      title: 'Sister Carrie',
      author: 'Theodore Dreiser',
      description: 'A young woman moves to the big city and becomes a kept woman.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1900,
      gutenbergId: '233',
      epubUrl: 'https://www.gutenberg.org/ebooks/233.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/233/pg233.cover.medium.jpg',
    },
    {
      title: 'The Souls of Black Folk',
      author: 'W.E.B. Du Bois',
      description: 'A seminal work in the history of sociology and civil rights.',
      language: 'EN' as const,
      genre: 'NON_FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1903,
      gutenbergId: '408',
      epubUrl: 'https://www.gutenberg.org/ebooks/408.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/408/pg408.cover.medium.jpg',
    },
    {
      title: 'Up from Slavery',
      author: 'Booker T. Washington',
      description: 'The autobiography of the famous African American educator.',
      language: 'EN' as const,
      genre: 'BIOGRAPHY' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1901,
      gutenbergId: '2376',
      epubUrl: 'https://www.gutenberg.org/ebooks/2376.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2376/pg2376.cover.medium.jpg',
    },
    {
      title: 'Narrative of the Life of Frederick Douglass',
      author: 'Frederick Douglass',
      description: 'The autobiography of the famous abolitionist and statesman.',
      language: 'EN' as const,
      genre: 'BIOGRAPHY' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1845,
      gutenbergId: '23',
      epubUrl: 'https://www.gutenberg.org/ebooks/23.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/23/pg23.cover.medium.jpg',
    },
    {
      title: 'Incidents in the Life of a Slave Girl',
      author: 'Harriet Jacobs',
      description: 'An autobiography documenting the authors experiences as a slave.',
      language: 'EN' as const,
      genre: 'BIOGRAPHY' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1861,
      gutenbergId: '11030',
      epubUrl: 'https://www.gutenberg.org/ebooks/11030.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/11030/pg11030.cover.medium.jpg',
    },
    // 스페인어 추가
    {
      title: 'Don Quijote de la Mancha',
      author: 'Miguel de Cervantes',
      description: 'La historia del caballero Don Quijote y su fiel escudero Sancho Panza.',
      language: 'ES' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1605,
      gutenbergId: '2000',
      epubUrl: 'https://www.gutenberg.org/ebooks/2000.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2000/pg2000.cover.medium.jpg',
    },
    {
      title: 'La Celestina',
      author: 'Fernando de Rojas',
      description: 'Una tragicomedia sobre el amor trágico de Calisto y Melibea.',
      language: 'ES' as const,
      genre: 'DRAMA' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1499,
      gutenbergId: '1619',
      epubUrl: 'https://www.gutenberg.org/ebooks/1619.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1619/pg1619.cover.medium.jpg',
    },
    {
      title: 'Lazarillo de Tormes',
      author: 'Anonymous',
      description: 'La primera novela picaresca española.',
      language: 'ES' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1554,
      gutenbergId: '320',
      epubUrl: 'https://www.gutenberg.org/ebooks/320.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/320/pg320.cover.medium.jpg',
    },
    // 중국어 추가
    {
      title: 'The Art of War',
      author: 'Sun Tzu',
      description: 'Ancient Chinese military treatise on strategy and tactics.',
      language: 'ZH' as const,
      genre: 'NON_FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: -500,
      gutenbergId: '132',
      epubUrl: 'https://www.gutenberg.org/ebooks/132.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/132/pg132.cover.medium.jpg',
    },
    {
      title: 'Tao Te Ching',
      author: 'Laozi',
      description: 'Classic Chinese text on Taoism and philosophy.',
      language: 'ZH' as const,
      genre: 'PHILOSOPHY' as const,
      difficulty: 'HARD' as const,
      publishedYear: -400,
      gutenbergId: '216',
      epubUrl: 'https://www.gutenberg.org/ebooks/216.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/216/pg216.cover.medium.jpg',
    },
    {
      title: 'Analects',
      author: 'Confucius',
      description: 'Collection of sayings and ideas attributed to the Chinese philosopher Confucius.',
      language: 'ZH' as const,
      genre: 'PHILOSOPHY' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: -475,
      gutenbergId: '3330',
      epubUrl: 'https://www.gutenberg.org/ebooks/3330.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/3330/pg3330.cover.medium.jpg',
    },
    // 일본어 추가
    {
      title: 'Kokoro',
      author: 'Natsume Soseki',
      description: 'A story exploring themes of loneliness, guilt, and human connection.',
      language: 'JA' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1914,
      gutenbergId: '759',
      epubUrl: 'https://www.gutenberg.org/ebooks/759.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/759/pg759.cover.medium.jpg',
    },
    {
      title: 'I Am a Cat',
      author: 'Natsume Soseki',
      description: 'A satirical novel narrated from the perspective of a cat.',
      language: 'JA' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1905,
      gutenbergId: '789',
      epubUrl: 'https://www.gutenberg.org/ebooks/789.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/789/pg789.cover.medium.jpg',
    },
    {
      title: 'Botchan',
      author: 'Natsume Soseki',
      description: 'A comedic story about a young teacher in rural Japan.',
      language: 'JA' as const,
      genre: 'FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1906,
      gutenbergId: '752',
      epubUrl: 'https://www.gutenberg.org/ebooks/752.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/752/pg752.cover.medium.jpg',
    },
    // 한국어 추가
    {
      title: 'The Story of Hong Gildong',
      author: 'Heo Gyun',
      description: 'The first Korean novel written in Hangul about a legendary hero.',
      language: 'KO' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1618,
      gutenbergId: '30168',
      epubUrl: 'https://www.gutenberg.org/ebooks/30168.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/30168/pg30168.cover.medium.jpg',
    },
    {
      title: 'The Tale of Chunhyang',
      author: 'Anonymous',
      description: 'A classic Korean love story between a nobleman and a commoner.',
      language: 'KO' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1754,
      gutenbergId: '30165',
      epubUrl: 'https://www.gutenberg.org/ebooks/30165.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/30165/pg30165.cover.medium.jpg',
    },
    // 더 많은 영어 책들
    {
      title: 'The Phantom of the Opera',
      author: 'Gaston Leroux',
      description: 'A mysterious phantom haunts the Paris Opera House.',
      language: 'EN' as const,
      genre: 'HORROR' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1910,
      gutenbergId: '175',
      epubUrl: 'https://www.gutenberg.org/ebooks/175.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/175/pg175.cover.medium.jpg',
    },
    {
      title: 'The Man Who Was Thursday',
      author: 'G.K. Chesterton',
      description: 'A philosophical thriller about a secret council of anarchists.',
      language: 'EN' as const,
      genre: 'MYSTERY' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1908,
      gutenbergId: '1695',
      epubUrl: 'https://www.gutenberg.org/ebooks/1695.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1695/pg1695.cover.medium.jpg',
    },
    {
      title: 'Father Brown Stories',
      author: 'G.K. Chesterton',
      description: 'Detective stories featuring the unassuming Catholic priest Father Brown.',
      language: 'EN' as const,
      genre: 'MYSTERY' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1911,
      gutenbergId: '223',
      epubUrl: 'https://www.gutenberg.org/ebooks/223.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/223/pg223.cover.medium.jpg',
    },
    {
      title: 'Herland',
      author: 'Charlotte Perkins Gilman',
      description: 'A utopian novel about a society composed entirely of women.',
      language: 'EN' as const,
      genre: 'SCIENCE_FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1915,
      gutenbergId: '32',
      epubUrl: 'https://www.gutenberg.org/ebooks/32.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/32/pg32.cover.medium.jpg',
    },
    {
      title: 'The Thirty-Nine Steps',
      author: 'John Buchan',
      description: 'A classic spy thriller about a man caught up in international intrigue.',
      language: 'EN' as const,
      genre: 'MYSTERY' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1915,
      gutenbergId: '558',
      epubUrl: 'https://www.gutenberg.org/ebooks/558.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/558/pg558.cover.medium.jpg',
    },
    {
      title: 'Kim',
      author: 'Rudyard Kipling',
      description: 'The story of an Irish orphan boy living in India.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1901,
      gutenbergId: '2226',
      epubUrl: 'https://www.gutenberg.org/ebooks/2226.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2226/pg2226.cover.medium.jpg',
    },
    {
      title: 'The Man in the Iron Mask',
      author: 'Alexandre Dumas',
      description: 'The final episode of the Three Musketeers saga.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1850,
      gutenbergId: '2759',
      epubUrl: 'https://www.gutenberg.org/ebooks/2759.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2759/pg2759.cover.medium.jpg',
    },
    {
      title: 'The Prisoner of Zenda',
      author: 'Anthony Hope',
      description: 'A classic adventure novel about an Englishman who impersonates a king.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1894,
      gutenbergId: '95',
      epubUrl: 'https://www.gutenberg.org/ebooks/95.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/95/pg95.cover.medium.jpg',
    },
    {
      title: 'The Scarlet Pimpernel',
      author: 'Baroness Orczy',
      description: 'A tale of a mysterious hero who rescues aristocrats during the French Revolution.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1905,
      gutenbergId: '60',
      epubUrl: 'https://www.gutenberg.org/ebooks/60.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/60/pg60.cover.medium.jpg',
    },
    {
      title: 'Babbitt',
      author: 'Sinclair Lewis',
      description: 'A satirical novel about American middle-class conformity.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1922,
      gutenbergId: '1156',
      epubUrl: 'https://www.gutenberg.org/ebooks/1156.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1156/pg1156.cover.medium.jpg',
    },
    {
      title: 'Main Street',
      author: 'Sinclair Lewis',
      description: 'A satirical view of small-town American life.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1920,
      gutenbergId: '543',
      epubUrl: 'https://www.gutenberg.org/ebooks/543.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/543/pg543.cover.medium.jpg',
    },
    {
      title: 'Anne of Green Gables',
      author: 'Lucy Maud Montgomery',
      description: 'The story of a spirited orphan girl sent to live on a farm.',
      language: 'EN' as const,
      genre: 'CHILDREN' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1908,
      gutenbergId: '45',
      epubUrl: 'https://www.gutenberg.org/ebooks/45.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/45/pg45.cover.medium.jpg',
    },
    {
      title: 'Pollyanna',
      author: 'Eleanor H. Porter',
      description: 'An optimistic orphan girl transforms a small town with her glad game.',
      language: 'EN' as const,
      genre: 'CHILDREN' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1913,
      gutenbergId: '1450',
      epubUrl: 'https://www.gutenberg.org/ebooks/1450.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1450/pg1450.cover.medium.jpg',
    },
    {
      title: 'The Wind in the Willows',
      author: 'Kenneth Grahame',
      description: 'A classic tale of the adventures of Mole, Rat, Badger, and Toad.',
      language: 'EN' as const,
      genre: 'CHILDREN' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1908,
      gutenbergId: '289',
      epubUrl: 'https://www.gutenberg.org/ebooks/289.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/289/pg289.cover.medium.jpg',
    },
    {
      title: 'Black Beauty',
      author: 'Anna Sewell',
      description: 'The autobiography of a horse and a call for the humane treatment of animals.',
      language: 'EN' as const,
      genre: 'CHILDREN' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1877,
      gutenbergId: '271',
      epubUrl: 'https://www.gutenberg.org/ebooks/271.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/271/pg271.cover.medium.jpg',
    },
    {
      title: 'The Voyages of Doctor Dolittle',
      author: 'Hugh Lofting',
      description: 'Adventures of a doctor who can talk to animals.',
      language: 'EN' as const,
      genre: 'CHILDREN' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1922,
      gutenbergId: '1154',
      epubUrl: 'https://www.gutenberg.org/ebooks/1154.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1154/pg1154.cover.medium.jpg',
    },
    {
      title: 'Heidi',
      author: 'Johanna Spyri',
      description: 'A young orphan girl is sent to live with her grandfather in the Swiss Alps.',
      language: 'EN' as const,
      genre: 'CHILDREN' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1881,
      gutenbergId: '1448',
      epubUrl: 'https://www.gutenberg.org/ebooks/1448.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1448/pg1448.cover.medium.jpg',
    },
  ];

  let count = 0;
  for (const book of extraBooks) {
    try {
      await prisma.book.upsert({
        where: { gutenbergId: book.gutenbergId },
        update: {},
        create: book,
      });
      count++;
    } catch (e) {
      console.log(`Skipped: ${book.title}`);
    }
  }

  console.log(`Created ${count} additional books`);

  const totalBooks = await prisma.book.count();
  console.log(`Total books in database: ${totalBooks}`);
  console.log('Extra seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
