import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // 관리자 계정 생성
  const adminPassword = await bcrypt.hash('admin123', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@pubstation.com' },
    update: {},
    create: {
      email: 'admin@pubstation.com',
      name: 'Admin',
      hashedPassword: adminPassword,
      role: 'ADMIN',
    },
  });
  console.log('Created admin:', admin.email);

  // 테스트 사용자 생성
  const userPassword = await bcrypt.hash('user1234', 12);
  const user = await prisma.user.upsert({
    where: { email: 'user@example.com' },
    update: {},
    create: {
      email: 'user@example.com',
      name: 'Test User',
      hashedPassword: userPassword,
      role: 'USER',
    },
  });
  console.log('Created user:', user.email);

  // 샘플 책 데이터 - 모두 표지가 있는 책들
  const sampleBooks = [
    {
      title: 'Pride and Prejudice',
      author: 'Jane Austen',
      description: 'A romantic novel following the turbulent relationship between Elizabeth Bennet and Mr. Darcy.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1813,
      gutenbergId: '1342',
      epubUrl: 'https://www.gutenberg.org/ebooks/1342.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg',
    },
    {
      title: 'Frankenstein',
      author: 'Mary Shelley',
      description: 'The story of Victor Frankenstein, a young scientist who creates a sapient creature.',
      language: 'EN' as const,
      genre: 'HORROR' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1818,
      gutenbergId: '84',
      epubUrl: 'https://www.gutenberg.org/ebooks/84.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg',
    },
    {
      title: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      description: 'A story of decadence and excess in the Jazz Age America.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1925,
      gutenbergId: '64317',
      epubUrl: 'https://www.gutenberg.org/ebooks/64317.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/64317/pg64317.cover.medium.jpg',
    },
    {
      title: 'A Tale of Two Cities',
      author: 'Charles Dickens',
      description: 'A historical novel set in London and Paris before and during the French Revolution.',
      language: 'EN' as const,
      genre: 'HISTORY' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1859,
      gutenbergId: '98',
      epubUrl: 'https://www.gutenberg.org/ebooks/98.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/98/pg98.cover.medium.jpg',
    },
    {
      title: 'The Adventures of Sherlock Holmes',
      author: 'Arthur Conan Doyle',
      description: 'A collection of twelve short stories featuring the detective Sherlock Holmes.',
      language: 'EN' as const,
      genre: 'MYSTERY' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1892,
      gutenbergId: '1661',
      epubUrl: 'https://www.gutenberg.org/ebooks/1661.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1661/pg1661.cover.medium.jpg',
    },
    {
      title: 'The Picture of Dorian Gray',
      author: 'Oscar Wilde',
      description: 'A philosophical novel about a young man whose portrait ages while he remains young.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1890,
      gutenbergId: '174',
      epubUrl: 'https://www.gutenberg.org/ebooks/174.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/174/pg174.cover.medium.jpg',
    },
    {
      title: 'Moby Dick',
      author: 'Herman Melville',
      description: 'The narrative of Captain Ahab obsessive quest to kill Moby Dick, the giant white sperm whale.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1851,
      gutenbergId: '2701',
      epubUrl: 'https://www.gutenberg.org/ebooks/2701.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2701/pg2701.cover.medium.jpg',
    },
    {
      title: 'Dracula',
      author: 'Bram Stoker',
      description: 'The classic vampire novel told through letters, diary entries, and newspaper articles.',
      language: 'EN' as const,
      genre: 'HORROR' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1897,
      gutenbergId: '345',
      epubUrl: 'https://www.gutenberg.org/ebooks/345.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/345/pg345.cover.medium.jpg',
    },
    {
      title: 'Alice in Wonderland',
      author: 'Lewis Carroll',
      description: 'A young girl named Alice falls through a rabbit hole into a fantasy world.',
      language: 'EN' as const,
      genre: 'FANTASY' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1865,
      gutenbergId: '11',
      epubUrl: 'https://www.gutenberg.org/ebooks/11.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/11/pg11.cover.medium.jpg',
    },
    {
      title: 'War and Peace',
      author: 'Leo Tolstoy',
      description: 'An epic novel chronicling French invasion of Russia and its impact on Tsarist society.',
      language: 'EN' as const,
      genre: 'HISTORY' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1869,
      gutenbergId: '2600',
      epubUrl: 'https://www.gutenberg.org/ebooks/2600.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2600/pg2600.cover.medium.jpg',
    },
    {
      title: 'Crime and Punishment',
      author: 'Fyodor Dostoevsky',
      description: 'A psychological drama about a poor ex-student who commits a murder.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1866,
      gutenbergId: '2554',
      epubUrl: 'https://www.gutenberg.org/ebooks/2554.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2554/pg2554.cover.medium.jpg',
    },
    {
      title: 'The Odyssey',
      author: 'Homer',
      description: 'The epic poem following Odysseus journey home after the fall of Troy.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'HARD' as const,
      publishedYear: -800,
      gutenbergId: '1727',
      epubUrl: 'https://www.gutenberg.org/ebooks/1727.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1727/pg1727.cover.medium.jpg',
    },
    {
      title: 'Jane Eyre',
      author: 'Charlotte Bronte',
      description: 'The story of a plain governess and her love for the brooding Mr. Rochester.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1847,
      gutenbergId: '1260',
      epubUrl: 'https://www.gutenberg.org/ebooks/1260.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg',
    },
    {
      title: 'Wuthering Heights',
      author: 'Emily Bronte',
      description: 'A wild, passionate story of the intense love between Catherine Earnshaw and Heathcliff.',
      language: 'EN' as const,
      genre: 'ROMANCE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1847,
      gutenbergId: '768',
      epubUrl: 'https://www.gutenberg.org/ebooks/768.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/768/pg768.cover.medium.jpg',
    },
    {
      title: 'The Count of Monte Cristo',
      author: 'Alexandre Dumas',
      description: 'An adventure novel about a man wrongly imprisoned who escapes and seeks revenge.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1844,
      gutenbergId: '1184',
      epubUrl: 'https://www.gutenberg.org/ebooks/1184.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1184/pg1184.cover.medium.jpg',
    },
    {
      title: 'Les Miserables',
      author: 'Victor Hugo',
      description: 'An epic novel following the lives of several characters in post-revolutionary France.',
      language: 'EN' as const,
      genre: 'HISTORY' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1862,
      gutenbergId: '135',
      epubUrl: 'https://www.gutenberg.org/ebooks/135.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/135/pg135.cover.medium.jpg',
    },
    {
      title: 'The Three Musketeers',
      author: 'Alexandre Dumas',
      description: 'The adventures of a young man who joins the Musketeers of the Guard.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1844,
      gutenbergId: '1257',
      epubUrl: 'https://www.gutenberg.org/ebooks/1257.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1257/pg1257.cover.medium.jpg',
    },
    {
      title: 'Twenty Thousand Leagues Under the Sea',
      author: 'Jules Verne',
      description: 'A classic science fiction novel about Captain Nemo and his submarine.',
      language: 'EN' as const,
      genre: 'SCIENCE_FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1870,
      gutenbergId: '164',
      epubUrl: 'https://www.gutenberg.org/ebooks/164.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/164/pg164.cover.medium.jpg',
    },
    {
      title: 'Around the World in Eighty Days',
      author: 'Jules Verne',
      description: 'Phileas Fogg wagers that he can circumnavigate the world in just eighty days.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1872,
      gutenbergId: '103',
      epubUrl: 'https://www.gutenberg.org/ebooks/103.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/103/pg103.cover.medium.jpg',
    },
    {
      title: 'The Time Machine',
      author: 'H.G. Wells',
      description: 'A scientist invents a machine that allows him to travel through time.',
      language: 'EN' as const,
      genre: 'SCIENCE_FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1895,
      gutenbergId: '35',
      epubUrl: 'https://www.gutenberg.org/ebooks/35.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/35/pg35.cover.medium.jpg',
    },
    {
      title: 'The War of the Worlds',
      author: 'H.G. Wells',
      description: 'A science fiction novel describing a Martian invasion of Earth.',
      language: 'EN' as const,
      genre: 'SCIENCE_FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1898,
      gutenbergId: '36',
      epubUrl: 'https://www.gutenberg.org/ebooks/36.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/36/pg36.cover.medium.jpg',
    },
    {
      title: 'Great Expectations',
      author: 'Charles Dickens',
      description: 'The story of the orphan Pip and his journey from poverty to gentility.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1861,
      gutenbergId: '1400',
      epubUrl: 'https://www.gutenberg.org/ebooks/1400.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/1400/pg1400.cover.medium.jpg',
    },
    {
      title: 'Oliver Twist',
      author: 'Charles Dickens',
      description: 'The story of an orphan boy who escapes a workhouse and falls in with thieves.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1838,
      gutenbergId: '730',
      epubUrl: 'https://www.gutenberg.org/ebooks/730.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/730/pg730.cover.medium.jpg',
    },
    {
      title: 'The Jungle Book',
      author: 'Rudyard Kipling',
      description: 'Stories about Mowgli, a boy raised by wolves in the Indian jungle.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1894,
      gutenbergId: '236',
      epubUrl: 'https://www.gutenberg.org/ebooks/236.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/236/pg236.cover.medium.jpg',
    },
    {
      title: 'Treasure Island',
      author: 'Robert Louis Stevenson',
      description: 'A classic tale of pirates, buried treasure, and adventure on the high seas.',
      language: 'EN' as const,
      genre: 'ADVENTURE' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1883,
      gutenbergId: '120',
      epubUrl: 'https://www.gutenberg.org/ebooks/120.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/120/pg120.cover.medium.jpg',
    },
    {
      title: 'The Strange Case of Dr Jekyll and Mr Hyde',
      author: 'Robert Louis Stevenson',
      description: 'A tale of the duality of human nature through a London lawyer investigation.',
      language: 'EN' as const,
      genre: 'HORROR' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1886,
      gutenbergId: '43',
      epubUrl: 'https://www.gutenberg.org/ebooks/43.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/43/pg43.cover.medium.jpg',
    },
    {
      title: 'Little Women',
      author: 'Louisa May Alcott',
      description: 'The story of the four March sisters growing up during the Civil War.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'EASY' as const,
      publishedYear: 1868,
      gutenbergId: '514',
      epubUrl: 'https://www.gutenberg.org/ebooks/514.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/514/pg514.cover.medium.jpg',
    },
    {
      title: 'The Hound of the Baskervilles',
      author: 'Arthur Conan Doyle',
      description: 'Sherlock Holmes investigates a supernatural hound haunting the Baskerville family.',
      language: 'EN' as const,
      genre: 'MYSTERY' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1902,
      gutenbergId: '2852',
      epubUrl: 'https://www.gutenberg.org/ebooks/2852.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/2852/pg2852.cover.medium.jpg',
    },
    {
      title: 'Heart of Darkness',
      author: 'Joseph Conrad',
      description: 'A journey into the African Congo that explores the darkness of human nature.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'HARD' as const,
      publishedYear: 1899,
      gutenbergId: '219',
      epubUrl: 'https://www.gutenberg.org/ebooks/219.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/219/pg219.cover.medium.jpg',
    },
    {
      title: 'The Scarlet Letter',
      author: 'Nathaniel Hawthorne',
      description: 'A story of sin, guilt, and redemption in Puritan Massachusetts.',
      language: 'EN' as const,
      genre: 'FICTION' as const,
      difficulty: 'MEDIUM' as const,
      publishedYear: 1850,
      gutenbergId: '25344',
      epubUrl: 'https://www.gutenberg.org/ebooks/25344.epub.images',
      coverUrl: 'https://www.gutenberg.org/cache/epub/25344/pg25344.cover.medium.jpg',
    },
  ];

  for (const book of sampleBooks) {
    await prisma.book.upsert({
      where: { gutenbergId: book.gutenbergId },
      update: {},
      create: book,
    });
  }

  console.log(`Created ${sampleBooks.length} sample books`);
  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
